name: Build Latest

on: 
  - push
  - workflow_dispatch

jobs:
  build-windows:
    uses: ./.github/workflows/build_windows.yml

  build-wiiu:
    uses: ./.github/workflows/build_wiiu.yml

  build-mac:
    uses: ./.github/workflows/build_mac.yml
